services:
  web:
    container_name: flash-app
    image: hongannguyen/flash-app:latest
    restart: always
    build: .
    ports:
      - "8080:80"

  flash-api:
    container_name: flash-api
    image: hongannguyen/flash-api:latest
    restart: always
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8010:8010"
    depends_on:
      - mongo

  mongo:
    container_name: "mongo"
    image: "mongo"
    restart: always
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"
