# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  slack: circleci/slack@4.1
  docker: circleci/docker@1.4.0
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-push:
    environment:
      DOCKER_IMAGE: hongannguyen/flash-cicd
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - slack/notify:
          channel: https://flash-cicd.slack.com/archives/C024CMVA4FM
          branch_pattern: main
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: https://flash-cicd.slack.com/archives/C024CMVA4FM
          branch_pattern: main
          event: pass
          template: success_tagged_deploy_1
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  # deploy:
  #   executor: docker/docker
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - $SSH_KEY_FINGERPRINT
  #     - run: ssh -oStrictHostKeyChecking=no -p 24700 $DEPLOYED_USER@$DEPLOYED_SERVER_IP "cd /home/delivery/customer && sh deploy.sh"

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  falsh-cicd:
    jobs:
      # - node/test
      - build-and-push:
          # requires:
          #   - node/test
          filters:
            branches:
              only:
                - main
